# Generated by Django 4.0.6 on 2022-07-09 09:50

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_classroom_i_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(validators=[classroom.models.negative_error]),
        ),
    ]
